# Astro Starlight サイトをビルドして GitHub Pages にデプロイするためのサンプルワークフロー
#
name: Deploy Documents to Pages

on:
  # `main` ブランチへのプッシュで実行されます。デフォルトブランチが `master` の場合は変更してください。
  push:
    branches: [main]

  # Actions タブから手動でワークフローを実行できるようにします
  workflow_dispatch:

# GITHUB_TOKEN の権限を設定して、GitHub Pages へのデプロイを許可します
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行を1つに制限し、進行中の実行と最新のキューの間の実行をスキップします。
# ただし、進行中の実行はキャンセルしません（本番デプロイの完了を許可するため）。
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # lastUpdated が有効でない場合は不要
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build with Astro
        run: pnpm --filter docs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/dist

  # デプロイジョブ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
